const $=s=>document.querySelector(s), key='zeefher-orbita-v1';let snapshot=null,result=null,busy=false;
try{snapshot=JSON.parse(localStorage.getItem(key)||'null')}catch{}
const money=n=>(n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function cell(row,text,cls){const el=document.createElement('td');el.textContent=text;if(cls)el.className=cls;row.append(el);return el}
function render(){if(!result)return;for(const [k,v] of Object.entries(result.metrics))$('#'+k).textContent=k==='value'?money(v):v.toLocaleString('pt-BR');
const category=$('#category').value;const cats=[...new Set(result.products.map(p=>p.category))].sort();$('#category').replaceChildren(new Option('Todas as categorias',''),...cats.map(c=>new Option(c,c)));$('#category').value=cats.includes(category)?category:'';$('#categories').replaceChildren(...cats.map(c=>new Option(c,c)));
const selected=$('#product-select').value;$('#product-select').replaceChildren(...result.products.map(p=>new Option(`${p.name} — saldo: ${p.stock}`,p.id)));if(result.products.some(p=>String(p.id)===selected))$('#product-select').value=selected;
$('#rows').replaceChildren();for(const p of filtered()){const row=document.createElement('tr');cell(row,p.name);cell(row,p.category);cell(row,money(p.price));cell(row,p.stock);cell(row,p.minimum);const tag=document.createElement('span');tag.className='pill'+(p.stock<=p.minimum?' low':'');tag.textContent=p.stock<=p.minimum?'Estoque baixo':'Regular';cell(row,'').append(tag);$('#rows').append(row)}if(!$('#rows').children.length){const row=document.createElement('tr');cell(row,'Nenhum produto encontrado.').colSpan=6;$('#rows').append(row)}
$('#logs').replaceChildren();for(const m of result.history){const row=document.createElement('tr');cell(row,new Date(m.created).toLocaleString('pt-BR'));cell(row,m.name);cell(row,(m.quantity>0?'+':'')+m.quantity,m.quantity>0?'positive':'negative');cell(row,m.note);$('#logs').append(row)}}
function filtered(){return result.products.filter(p=>p.name.toLocaleLowerCase('pt-BR').includes($('#search').value.toLocaleLowerCase('pt-BR'))&&(!$('#category').value||p.category===$('#category').value)&&(!$('#onlylow').checked||p.stock<=p.minimum))}
async function request(action='list',data={}){if(busy)return false;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);$('#status').textContent='Processando…';try{const response=await fetch('/api/stock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:snapshot,action,data})});const next=await response.json();if(!response.ok)throw Error(next.error||'Não foi possível concluir.');result=next;snapshot=next.state;let saved=true;try{localStorage.setItem(key,JSON.stringify(snapshot))}catch{saved=false}render();$('#status').textContent=saved?(action==='list'?'Estoque atualizado.':'Operação registrada com sucesso.'):'Operação concluída, mas o navegador não permitiu salvar. Os dados serão perdidos ao fechar.';return true}catch(e){$('#status').textContent=e.message==='Failed to fetch'?'Falha de conexão. Tente novamente.':e.message;return false}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false)}}
$('#product-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(await request('product',{name:f.get('name'),category:f.get('category'),price:Math.round(Number(f.get('price'))*100),minimum:Number(f.get('minimum'))}))e.target.reset()};
$('#move-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(await request('move',{product_id:Number(f.get('product_id')),quantity:Number(f.get('quantity'))*Number(f.get('direction')),note:f.get('note')}))e.target.reset()};
for(const id of ['search','category','onlylow'])$('#'+id).addEventListener('input',render);
$('#reset').onclick=async()=>{if(confirm('Restaurar os dados fictícios e descartar suas alterações nesta demonstração?')){const previous=snapshot;snapshot=null;if(!await request())snapshot=previous}};
$('#csv').onclick=()=>{if(!result)return;const safe=v=>'"'+String(v).replace(/^[=+@\-]/,"'$&").replaceAll('"','""')+'"';const lines=[['Produto','Categoria','Preço (R$)','Saldo','Mínimo'],...filtered().map(p=>[p.name,p.category,(p.price/100).toFixed(2).replace('.',','),p.stock,p.minimum])];const url=URL.createObjectURL(new Blob(['\ufeff'+lines.map(r=>r.map(safe).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='orbita-estoque.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};request();
