const $=s=>document.querySelector(s);let csv='',result=null,busy=false;
const money=n=>(n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function download(name,content){const u=URL.createObjectURL(new Blob(['\ufeff'+content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function chart(id,rows){const box=$('#'+id);box.replaceChildren();if(!rows.length){box.textContent='Sem vendas neste período.';return}const max=Math.max(...rows.map(r=>r.value),1);for(const r of rows){const item=document.createElement('div');item.className='barrow';const label=document.createElement('div'),name=document.createElement('span'),val=document.createElement('span');name.textContent=r.label;val.textContent=money(r.value);label.append(name,val);const bar=document.createElement('i');bar.style.width=(100*r.value/max)+'%';bar.setAttribute('aria-hidden','true');item.append(label,bar);box.append(item)}}
function render(){for(const id of ['revenue','orders','ticket','units'])$('#'+id).textContent=['revenue','ticket'].includes(id)?money(result[id]):result[id];$('#comparison').textContent=result.change===null?'Sem receita na base anterior':(result.change>0?'+':'')+result.change+'% sobre o período anterior';$('#period').textContent='Período: '+result.start+' a '+result.end+'. Comparação: '+result.previous_start+' a '+result.previous_end+' ('+money(result.previous)+').';$('#start').value=result.start;$('#end').value=result.end;const selected=$('#category').value;$('#category').replaceChildren(new Option('Todas',''),...result.categories.map(c=>new Option(c,c)));$('#category').value=selected;chart('daily',result.daily);chart('products',result.products);const q=result.quality;$('#quality').textContent=q.total+' linhas lidas · '+q.valid+' válidas · '+q.duplicates+' duplicadas removidas · '+q.invalid+' inválidas excluídas. '+result.selected+' linhas no filtro.';$('#issues').replaceChildren();for(const i of result.issues){const tr=document.createElement('tr');for(const value of [i.linha,i.motivo]){const td=document.createElement('td');td.textContent=value;tr.append(td)}$('#issues').append(tr)}if(!result.issues.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=2;td.textContent='Nenhuma linha excluída.';tr.append(td);$('#issues').append(tr)}}
async function analyze(reset=false){if(busy)return;busy=true;document.querySelectorAll('button,input,select').forEach(x=>x.disabled=true);$('#status').textContent='Analisando CSV…';try{const response=await fetch('/api/pulso',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csv,start:reset?'':$('#start').value,end:reset?'':$('#end').value,category:reset?'':$('#category').value})});const data=await response.json();if(!response.ok)throw Error(data.error||'Falha na análise.');result=data;if(reset)$('#category').value='';render();$('#status').textContent='Análise concluída.'}catch(e){result=null;$('#status').textContent='Não foi possível analisar: '+e.message+' Os indicadores anteriores, se visíveis, não correspondem a esta tentativa.'}finally{busy=false;document.querySelectorAll('button,input,select').forEach(x=>x.disabled=false);$('#report').disabled=!result}}
async function example(){if(busy)return;try{const r=await fetch('/pulso/exemplo.csv');if(!r.ok)throw Error('Exemplo indisponível.');csv=await r.text();$('#file').value='';await analyze(true)}catch(e){$('#status').textContent=e.message}}
$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>500000){$('#status').textContent='O limite é 500 KB.';return}csv=await f.text();await analyze(true)};
$('#example').onclick=example;$('#filters').onsubmit=e=>{e.preventDefault();analyze()};
$('#report').onclick=()=>{if(!result)return;const r=result;const rows=[['Indicador','Valor'],['Período inicial',r.start],['Período final',r.end],['Receita (R$)',(r.revenue/100).toFixed(2)],['Pedidos',r.orders],['Ticket médio (R$)',(r.ticket/100).toFixed(2)],['Unidades',r.units],['Receita anterior (R$)',(r.previous/100).toFixed(2)],['Variação (%)',r.change??'Sem base'],['Linhas válidas',r.quality.valid],['Duplicatas removidas',r.quality.duplicates],['Linhas inválidas',r.quality.invalid],[],['Produto','Receita (R$)'],...r.products.map(p=>[p.label,(p.value/100).toFixed(2)]),[],['Linha excluída','Motivo'],...r.issues.map(i=>[i.linha,i.motivo])];const escape=v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';download('pulso-relatorio.csv',rows.map(row=>row.map(escape).join(';')).join('\r\n'))};example();
